# Generated by Django 3.0.4 on 2020-09-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=200, null=True)),
                ('Year', models.CharField(max_length=10, null=True)),
                ('Rated', models.CharField(max_length=10, null=True)),
                ('Released', models.CharField(max_length=20, null=True)),
                ('Runtime', models.CharField(max_length=20, null=True)),
                ('Genre', models.CharField(max_length=200, null=True)),
                ('Director', models.CharField(max_length=50, null=True)),
                ('Writer', models.TextField(null=True)),
                ('Actors', models.TextField(null=True)),
                ('Plot', models.TextField(null=True)),
                ('Language', models.CharField(max_length=200, null=True)),
                ('Country', models.CharField(max_length=200, null=True)),
                ('Awards', models.CharField(max_length=200, null=True)),
                ('Poster', models.TextField(null=True)),
                ('Ratings', models.TextField(null=True)),
                ('Metascore', models.CharField(max_length=10, null=True)),
                ('imdbID', models.CharField(max_length=20, null=True)),
                ('Type', models.CharField(max_length=20, null=True)),
                ('DVD', models.CharField(max_length=20, null=True)),
                ('BoxOffice', models.CharField(max_length=20, null=True)),
                ('Production', models.CharField(max_length=20, null=True)),
                ('Website', models.TextField(null=True)),
                ('Response', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
