# Generated by Django 3.0.4 on 2020-09-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='Actors',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Awards',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='BoxOffice',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='DVD',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Director',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Genre',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Metascore',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Plot',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Production',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Rated',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Ratings',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Released',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Response',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Runtime',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Website',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='Writer',
        ),
    ]
